from selenium.webdriver.common.by import By


class MainMenuLocators:
    LOGIN = (By.CSS_SELECTOR, 'input.ng-untouched.ng-pristine.ng-valid')
    PASSWORD = (By.CSS_SELECTOR, 'input.ng-untouched.ng-pristine.ng-invalid')
    ENTER = (By.CSS_SELECTOR, 'button.btn-login')


class CoreLocators:
    BUTTONCORE = (By.CSS_SELECTOR, '[title="Управление ролями и пользователями"]')
    COMPANYBUTTON = (By.CSS_SELECTOR, '.menu .ng-star-inserted .menu-item-wrapper.ng-star-inserted')
    CREATEUSER = (By.CSS_SELECTOR, '#main > app-root > div > app-company > app-users > div > div.header > button')
    INNAME = (By.CSS_SELECTOR, '[placeholder="Имя"]')
    INSECONDNAME = (By.CSS_SELECTOR, '[placeholder="Фамилия"]')
    INTHIRDNAME = (By.CSS_SELECTOR, '[placeholder="Отчество"]')
    INMAIL = (By.CSS_SELECTOR, '[placeholder="Email"]')
    ROLE1 = (By.CSS_SELECTOR, '#main > app-root > app-modals > div > div.modal-wrapper.sidebar > div.content > app-user-create-form > div > form > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > vc-select > div > div')
    ROLE2 = (By.CSS_SELECTOR, '#main > app-root > app-modals > div > div.modal-wrapper.sidebar > div.content > app-user-create-form > div > form > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > vc-select > div > div.select-list-wrapper.ng-star-inserted')
    DISTR1 = (By.CSS_SELECTOR, '#main > app-root > app-modals > div > div.modal-wrapper.sidebar > div.content > app-user-create-form > div > form > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > vc-select > div > div')
    DISTR2 = (By.CSS_SELECTOR, '#main > app-root > app-modals > div > div.modal-wrapper.sidebar > div.content > app-user-create-form > div > form > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > vc-select > div > div.select-list-wrapper.ng-star-inserted')
    LOGIN = (By.CSS_SELECTOR, '[placeholder="Логин"]')
    PASS = (By.CSS_SELECTOR, '[placeholder="Пароль"]')
    REPASS = (By.CSS_SELECTOR, '[placeholder="Подтверждение пароля"]')
    SCROLL = (By.CSS_SELECTOR, '#main > app-root > app-modals > div > div.modal-wrapper.sidebar > div.content > app-user-create-form > div > form > div:nth-child(2) > p')
    CHANNEL = (By.CSS_SELECTOR, '#main > app-root > app-modals > div > div.modal-wrapper.sidebar >div.content > app-user-create-form > div > form > div:nth-child(2)> div:nth-child(9) > div:nth-child(1) > div.flex-7.w-300-hard.flex.flex-v-center.ng-untouched.ng-pristine.ng-invalid > app-badge-checkbox:nth-child(1) > label')
    PARENT1 = (By.CSS_SELECTOR, '#main > app-root > app-modals > div > div.modal-wrapper.sidebar > div.content > app-user-create-form > div > form > div:nth-child(2) > div:nth-child(6) > div:nth-child(1) > div.flex-7.w-300-hard > vc-select > div > div')
    PARENT2 = (By.CSS_SELECTOR, '#main > app-root > app-modals > div > div.modal-wrapper.sidebar > div.content > app-user-create-form > div > form > div:nth-child(2) > div:nth-child(6) > div:nth-child(1) > div.flex-7.w-300-hard > vc-select > div > div.select-list-wrapper.ng-star-inserted')
    CREATE = (By.CSS_SELECTOR, '#main > app-root > app-modals > div > div.modal-wrapper.sidebar > div.content > app-user-create-form > footer > div.flex-1.flex.flex-v-center.flex-h-center > button')
    EDIT = (By.CSS_SELECTOR, '#main > app-root > div > app-company > app-users > div > div.table-wrapper > div.table-content > div:nth-child(1) > div.row-content')
    DELETE = (By.CSS_SELECTOR, '#main > app-root > app-modals > div > div.modal-wrapper.sidebar > div.content > app-user-create-form > footer > a')
    AGREE = (By.CSS_SELECTOR, '#main > app-root > app-modals > div:nth-child(2) > div.modal-wrapper > div.content > app-confirm > div.footer > button')


class DistributorLocators:
    LOGIN = (By.NAME, 'login')
    PASSWORD = (By.CSS_SELECTOR, '[name="password"]')
    ENTER = (By.CSS_SELECTOR, '[value="Войти"]')
    ORDERS = (By.CSS_SELECTOR, '#leftNavigation > div.wrapNav > ul > li.pointOrders')
    ORDERSEXCEL = (By.CSS_SELECTOR, '#main > section > header > div.mainFilters > span > div > a.getExcel')


class JeansLocators:
    BUTTONJEANS = (By.CSS_SELECTOR, '[title="Web-приложение для управления работой команды продаж"]')
    SP = (By.CSS_SELECTOR, 'li.ng-scope:nth-child(3) > a:nth-child(1)')
    CREATESP = (By.CSS_SELECTOR, 'div .toolbar.ng-scope .toolbar.filter-options-wrap.mb15 .btn.btn-primary.pull-left.mt10.w150.ml5.ng-scope')
    STATUSSPCLICK = (By.NAME, 'Status')
    STATUSSPCHOOSE = (By.CSS_SELECTOR, '#Status > ul:nth-child(3)')
    NAMESP = (By.ID, 'Name')
    CHANNELCLICK = (By.ID, 'Channel')
    CHANNELCHOOSE = (By.ID, 'ui-select-choices-5')
    ADRES = (By.ID, 'Address')
    TERRITORYCLICK = (By.NAME, 'Region')
    TERRITORYCHOOSE = (By.CSS_SELECTOR, '#Region > ul:nth-child(3)')
    REGIONCLICK = (By.NAME, 'RegionElement')
    REGIONCHOOSE = (By.CSS_SELECTOR, '#RegionElement > ul:nth-child(3)')
    CITY = (By.ID, 'CityElement')
    CITYCHOSE = (By.CSS_SELECTOR, '#CityElement > ul:nth-child(3)')
    DISTRCLICK = (By.NAME, 'Distributor')
    DISTRCHOOSE = (By.CSS_SELECTOR, '#Distributor > ul:nth-child(3)')
    WAREHOUSE = (By.NAME, 'Warehouse')
    WAREHOUSECHOOSE = (By.CSS_SELECTOR, '#Warehouse > ul:nth-child(3)')
    SALESAREA = (By.NAME, 'SalesArea')
    SAVESP = (By.CSS_SELECTOR, '[ng-if="Create || updateSP"]')
    FIND = (By.CSS_SELECTOR, '[placeholder="Поиск"]')
    EDITSP = (By.CSS_SELECTOR, 'div.Table-row:nth-child(2) > div:nth-child(6) > div:nth-child(2) > div:nth-child(1) > i:nth-child(1)')
    CHANGEFILTERSP = (By.CSS_SELECTOR, '.w200 > div:nth-child(1)')
    CHOOSESPFILTER = (By.CSS_SELECTOR, '.w200 > ul:nth-child(3)')
    SKUASSORT = (By.CSS_SELECTOR, 'li.ng-scope:nth-child(4) > a:nth-child(1)')
    SUBMENU = (By.CSS_SELECTOR, '[href="./sku/promotions/"]')
    CREATEPROMO = (By.CSS_SELECTOR, '[ng-click="CreatePromotions()"]')
    NAMEPROMO = (By.CSS_SELECTOR, '[ng-model="model.Name"]')
    TERMSPROMO = (By.CSS_SELECTOR, '[ng-model="model.Terms"]')
    DATEFROMPROMO = (By.CSS_SELECTOR, 'body > div.modal.fade.ng-isolate-scope.false.in > div > div > div > div.df.pt10 > div.block.w470.pt10 > div.block-form > div.dib.wide.block-form_period > div.col-sm-5 > div > input')
    DATETOFROM = (By.CSS_SELECTOR, 'body > div.modal.fade.ng-isolate-scope.false.in > div > div > div > div.df.pt10 > div.block.w470.pt10 > div.block-form > div.dib.wide.block-form_period > div.col-sm-4 > div > input')
    DISCOUNT1 = (By.CSS_SELECTOR, 'body > div.modal.fade.ng-isolate-scope.false.in > div > div > div > div.df.pt10 > div.block.w470.pt10 > div.block-form > div:nth-child(6) > div > div > div > span')
    DISCOUNT2 = (By.CSS_SELECTOR, 'body > div.modal.fade.ng-isolate-scope.false.in > div > div > div > div.df.pt10 > div.block.w470.pt10 > div.block-form > div:nth-child(6) > div > div > ul')
    DISCOUNT3 = (By.CSS_SELECTOR, 'body > div.modal.fade.ng-isolate-scope.false.in > div > div > div > div.df.pt10 > div.block.w470.pt10 > div.block-form > div:nth-child(7) > div > div > div > span')
    DISCOUNT4 = (By.CSS_SELECTOR, 'body > div.modal.fade.ng-isolate-scope.false.in > div > div > div > div.df.pt10 > div.block.w470.pt10 > div.block-form > div:nth-child(7) > div > div > ul')
    AUTOIN = (By.CSS_SELECTOR, '[Placeholder="Автозаполнение"]')
    SKUPROMO = (By.CSS_SELECTOR, '#Id115')
    SAVEPROMO = (By.CSS_SELECTOR, 'body > div.modal.fade.ng-isolate-scope.false.in > div > div > div > div:nth-child(3) > button.btn.btn-primary.ng-scope')
    VISIT = (By.CSS_SELECTOR, 'li.ng-scope:nth-child(6) > a:nth-child(1)')
    DATEFROMVISIT1 = (By.CSS_SELECTOR, 'body > div.main-view.container-fluid.plr0.ng-scope > div.container.ng-scope > div > div > div.row.toolbar.wide.mt0.mr0.mb0.ml0 > div > div:nth-child(3)')
    DATEFROMVISIT2 = (By.CSS_SELECTOR, 'body > div.main-view.container-fluid.plr0.ng-scope > div.container.ng-scope > div > div > div.row.toolbar.wide.mt0.mr0.mb0.ml0 > div > div:nth-child(3) > div > div > input')
    DATETOVISIT1 = (By.CSS_SELECTOR, 'body > div.main-view.container-fluid.plr0.ng-scope > div.container.ng-scope > div > div > div.row.toolbar.wide.mt0.mr0.mb0.ml0 > div > div:nth-child(4)')
    DATETOVISIT2 = (By.CSS_SELECTOR, 'body > div.main-view.container-fluid.plr0.ng-scope > div.container.ng-scope > div > div > div.row.toolbar.wide.mt0.mr0.mb0.ml0 > div > div:nth-child(4) > div > div > input')
    VISITBIND = (By.CSS_SELECTOR, '#routing-table-wrap > div:nth-child(2) > div > div:nth-child(4)')
    SAVEVISIT = (By.CSS_SELECTOR, '[ng-click="saveVisits()"]')

class TimLocators:
    BUTTONTIM = (By.CSS_SELECTOR, '[title="Web-приложение для управления торговыми инвестициями."]')
    CREATECONTRACT = (By.CSS_SELECTOR, '[href="./contracts/create/"]')
    DISTRTIM1 = (By.CSS_SELECTOR, '.ftest_new-c-distributor > div:nth-child(1) > div:nth-child(1) > span:nth-child(1)')
    DISTRTIM2 = (By.CSS_SELECTOR, '#left-panel > ng-include:nth-child(1) > section > div:nth-child(2) > div > div > div > div > ul')
    DATEFROMCONTRACT = (By.CSS_SELECTOR, '#left-panel > ng-include:nth-child(1) > section > div:nth-child(4) > div > div.input-group.ui-select.calendar-input.ftest_new-c-valid-from > input')
    DATETOCONTRACT = (By.CSS_SELECTOR, '#left-panel > ng-include:nth-child(1) > section > div:nth-child(4) > div > div.input-group.ui-select.calendar-input.ftest_new-c-valid-to > input')
    DISCOUNTVALUECONTRACT = (By.CSS_SELECTOR, 'input.ng-valid-float:nth-child(2)')
    TERMCONTRACT1 = (By.CSS_SELECTOR, '#left-panel > ng-include:nth-child(2) > section > div > ul > li:nth-child(3) > a')
    TERMCONTRACT2 = (By.CSS_SELECTOR, '#left-panel > ng-include:nth-child(2) > section > div > div > div.tab-pane.ng-scope.active > ng-include > div.table-body.table-body-table-2.ng-scope > div.table-body-condition.table-body-condition-abs > div.table-body_body > div > div.table-body_body__row__column.long-table-target-input > input')
    SALECOTRACT1 = (By.CSS_SELECTOR, '#left-panel > ng-include:nth-child(2) > section > div > ul > li:nth-child(4) > a > uib-tab-heading')
    SALECOTRACT2 = (By.CSS_SELECTOR, '[ng-model="data.PlanRub"]')
    SAVECONTRACT = (By.CSS_SELECTOR, '#contract-wrapper > ng-include:nth-child(3) > div > button')
    CONTRACTMODULE = (By.CSS_SELECTOR, '#navigation-list > div:nth-child(5) > li > a')
    DRAFTLIST = (By.CSS_SELECTOR, 'div.table-body:nth-child(1) > div:nth-child(1)')
    DRAFTMOVE = (By.CSS_SELECTOR, 'div.block-line:nth-child(2) > div:nth-child(15) > button:nth-child(2) > i:nth-child(1)')